app = "concord-ws"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  MIX_ENV = "prod"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # Blue-green deployment settings
  min_machines_running = 2  # Ensure we have capacity for both versions
  auto_stop_machines = false  # Prevent automatic scaling down
  auto_start_machines = true
  soft_stop = true  # Enable graceful shutdown
  force_https = true
  routers = 2  # Multiple routers for high availability

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "20s"
    path = "/health"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "bluegreen"  # Enable blue-green deployment
  release_command = "mix deps.get && mix deps.compile" 