app = "concord-ws"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  MIX_ENV = "prod"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  soft_stop = true
  routers = 2

  [[http_service.checks]]
    grace_period = "120s"
    interval = "30s"
    method = "GET"
    timeout = "30s"
    path = "/health"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "bluegreen"
  release_command = "mix deps.get && mix deps.compile"
  wait_timeout = "300s" 