export const GUILD_PERMISSIONS = {
  ADMINISTRATOR: BigInt(1) << BigInt(0),
  MANAGE_GUILD: BigInt(1) << BigInt(1),
  MANAGE_ROLES: BigInt(1) << BigInt(2),
  MANAGE_CHANNELS: BigInt(1) << BigInt(3),
  MANAGE_MESSAGES: BigInt(1) << BigInt(4),
  MANAGE_NICKNAMES: BigInt(1) << BigInt(5),
  KICK_MEMBERS: BigInt(1) << BigInt(6),
  BAN_MEMBERS: BigInt(1) << BigInt(7),
  CREATE_INVITES: BigInt(1) << BigInt(8),
  SEND_MESSAGES: BigInt(1) << BigInt(9),
  EMBED_LINKS: BigInt(1) << BigInt(10),
  ATTACH_FILES: BigInt(1) << BigInt(11),
  ADD_REACTIONS: BigInt(1) << BigInt(12),
  MENTION_EVERYONE: BigInt(1) << BigInt(13),
  VIEW_CHANNELS: BigInt(1) << BigInt(14),
} as const;
