name: Production Deployment

on:
  push:
    branches: [master]
    paths:
      - 'web/**'
      - 'server/**'
      - 'ws/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    environment: production
    concurrency: production_server
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API
        run: |
          flyctl secrets set \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            DISCORD_CLIENT_ID="${{ secrets.DISCORD_CLIENT_ID }}" \
            DISCORD_CLIENT_SECRET="${{ secrets.DISCORD_CLIENT_SECRET }}" \
            GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            GITHUB_CLIENT_ID="${{ secrets.GITHUB_CLIENT_ID }}" \
            GITHUB_CLIENT_SECRET="${{ secrets.GITHUB_CLIENT_SECRET }}" \
            --app concord-api

          flyctl deploy --remote-only --app concord-api \
            --dockerfile Dockerfile \
            --config fly.toml \
            --env URL="https://concord-api.fly.dev" \
            --env CORS_ORIGIN="https://concord-web.fly.dev" \
            --env ALLOWED_ORIGINS="https://concord-web.fly.dev,wss://concord-ws.fly.dev" \
            --env NODE_ENV="production" \
            --strategy bluegreen \
            --wait-timeout 300
            --local-only
        working-directory: ./server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-ws:
    name: Deploy WebSocket
    runs-on: ubuntu-latest
    environment: production
    concurrency: production_ws
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy WebSocket
        run: |
          flyctl deploy --remote-only --app concord-ws \
            --dockerfile Dockerfile \
            --config fly.toml \
            --env URL="wss://concord-ws.fly.dev" \
            --env CORS_ORIGIN="https://concord-web.fly.dev" \
            --env MIX_ENV="prod" \
            --strategy bluegreen \
            --wait-timeout 300
            --local-only
        working-directory: ./ws
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-web:
    name: Deploy Web
    needs: [deploy-server, deploy-ws]
    runs-on: ubuntu-latest
    environment: production
    concurrency: production_web
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Web
        run: |
          flyctl deploy --remote-only --app concord-web \
            --dockerfile Dockerfile \
            --config fly.toml \
            --env NEXT_PUBLIC_URL="https://concord-web.fly.dev" \
            --env NEXT_PUBLIC_API_URL="https://concord-api.fly.dev" \
            --env NEXT_PUBLIC_WS_URL="wss://concord-ws.fly.dev" \
            --env NODE_ENV="production" \
            --strategy bluegreen \
            --wait-timeout 300
            --local-only
        working-directory: ./web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
