name: Fly Deploy
on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
      - dev

jobs:
  test-web:
    name: Test Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Fix Git configuration
        run: |
          # Remove any existing submodule configurations
          if [ -f .gitmodules ]; then
            rm .gitmodules
          fi

          # Clean up git config
          git config --local --unset-all submodule.web.url || true
          git config --local --unset-all submodule.web.active || true

          # Remove submodule directories if they exist
          rm -rf .git/modules/web || true

          # Ensure the web directory exists
          mkdir -p web

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: false

      - name: Install Dependencies
        run: |
          git config --global core.hooksPath /dev/null
          git config --global advice.detachedHead false
          pnpm install --ignore-scripts --no-frozen-lockfile --shamefully-hoist
        env:
          HUSKY: '0'
          HUSKY_SKIP_INSTALL: '1'
          NODE_OPTIONS: '--max_old_space_size=4096'
          CI: true
          PNPM_HOME: ${{ runner.temp }}/pnpm
          GIT_TERMINAL_PROMPT: '0'

      - name: Run Web Tests
        working-directory: ./web
        run: pnpm test

  test-server:
    name: Test Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: ./server
        run: bun install

      - name: Run Server Tests
        working-directory: ./server
        run: bun test

  deploy-production:
    name: Deploy Production
    needs: [test-web, test-server]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    concurrency: production_environment
    env:
      PROD_API_URL: https://api.concord.fly.dev
      PROD_WEB_URL: https://concord.fly.dev
      PROD_WS_URL: wss://ws.concord.fly.dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy API first
      - name: Deploy API to Production
        run: |
          flyctl deploy --remote-only --app concord-api \
            --dockerfile server/Dockerfile \
            --env DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}" \
            --env URL="${PROD_API_URL}" \
            --env CORS_ORIGIN="${PROD_WEB_URL}" \
            --env ALLOWED_ORIGINS="${PROD_WEB_URL},${PROD_WS_URL}" \
            --env DISCORD_CLIENT_ID="${{ secrets.PROD_DISCORD_CLIENT_ID }}" \
            --env DISCORD_CLIENT_SECRET="${{ secrets.PROD_DISCORD_CLIENT_SECRET }}" \
            --env GOOGLE_CLIENT_ID="${{ secrets.PROD_GOOGLE_CLIENT_ID }}" \
            --env GOOGLE_CLIENT_SECRET="${{ secrets.PROD_GOOGLE_CLIENT_SECRET }}" \
            --env GITHUB_CLIENT_ID="${{ secrets.PROD_GITHUB_CLIENT_ID }}" \
            --env GITHUB_CLIENT_SECRET="${{ secrets.PROD_GITHUB_CLIENT_SECRET }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Then deploy Web
      - name: Deploy Web to Production
        run: |
          flyctl deploy --remote-only --app concord-web \
            --dockerfile web/Dockerfile \
            --env NEXT_PUBLIC_URL="${PROD_WEB_URL}" \
            --env NEXT_PUBLIC_API_URL="${PROD_API_URL}" \
            --env NEXT_PUBLIC_WS_URL="${PROD_WS_URL}" \
            --env NODE_ENV="production"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Deploy WebSocket server
      - name: Deploy WebSocket to Production
        run: |
          flyctl deploy --remote-only --app concord-ws \
            --dockerfile ws/Dockerfile \
            --config ws/fly.toml \
            --env URL="${PROD_WS_URL}" \
            --env CORS_ORIGIN="${PROD_WEB_URL}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-staging:
    name: Deploy Staging
    needs: [test-web, test-server]
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging_environment
    env:
      STAGING_API_URL: https://staging.api.concord.fly.dev
      STAGING_WEB_URL: https://staging.concord.fly.dev
      STAGING_WS_URL: wss://staging.ws.concord.fly.dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy API first
      - name: Deploy API to Staging
        run: |
          flyctl deploy --remote-only --app concord-api-staging \
            --env DATABASE_URL="${{ secrets.STAGING_DATABASE_URL }}" \
            --env URL="${STAGING_API_URL}" \
            --env CORS_ORIGIN="${STAGING_WEB_URL}" \
            --env ALLOWED_ORIGINS="${STAGING_WEB_URL},${STAGING_WS_URL}" \
            --env DISCORD_CLIENT_ID="${{ secrets.STAGING_DISCORD_CLIENT_ID }}" \
            --env DISCORD_CLIENT_SECRET="${{ secrets.STAGING_DISCORD_CLIENT_SECRET }}" \
            --env GOOGLE_CLIENT_ID="${{ secrets.STAGING_GOOGLE_CLIENT_ID }}" \
            --env GOOGLE_CLIENT_SECRET="${{ secrets.STAGING_GOOGLE_CLIENT_SECRET }}" \
            --env GITHUB_CLIENT_ID="${{ secrets.STAGING_GITHUB_CLIENT_ID }}" \
            --env GITHUB_CLIENT_SECRET="${{ secrets.STAGING_GITHUB_CLIENT_SECRET }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Then deploy Web
      - name: Deploy Web to Staging
        run: |
          flyctl deploy --remote-only --app concord-web-staging \
            --dockerfile web/Dockerfile \
            --env NEXT_PUBLIC_URL="${STAGING_WEB_URL}" \
            --env NEXT_PUBLIC_API_URL="${STAGING_API_URL}" \
            --env NEXT_PUBLIC_WS_URL="${STAGING_WS_URL}" \
            --env NODE_ENV="production"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Deploy WebSocket server
      - name: Deploy WebSocket to Staging
        run: |
          flyctl deploy --remote-only --app concord-ws-staging \
            --config ws/fly.toml \
            --env URL="${STAGING_WS_URL}" \
            --env CORS_ORIGIN="${STAGING_WEB_URL}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
