name: Pull Request Checks

on:
  pull_request:
    branches: [master, staging]
    paths:
      - 'web/**'
      - 'server/**'
      - 'ws/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  test-all:
    name: Test All Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup environments
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - uses: pnpm/action-setup@v2
        with:
          version: '8.15.4'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'

      # Install dependencies
      - name: Install Web Dependencies
        run: cd web && pnpm install

      - name: Install Server Dependencies
        run: cd server && bun install

      - name: Install WS Dependencies
        run: |
          cd ws
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      # Run tests
      - name: Test Web
        run: cd web && pnpm test

      - name: Test Server
        run: cd server && bun test

      - name: Test WS
        run: cd ws && mix test
