name: WebSocket Staging CI/CD

on:
  push:
    branches: [staging]
    paths:
      - 'ws/**'
      - '.github/workflows/ws-staging.yml'

jobs:
  test:
    name: Test WebSocket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'

      - name: Install Dependencies
        working-directory: ./ws
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run Tests
        working-directory: ./ws
        run: mix test

  deploy:
    name: Deploy WebSocket Staging
    needs: test
    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging_ws

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging
        run: |
          flyctl deploy --remote-only --app concord-ws-staging \
            --dockerfile Dockerfile \
            --config fly.toml \
            --env URL="wss://staging.ws.concord.fly.dev" \
            --env CORS_ORIGIN="https://staging.concord.fly.dev" \
            --env MIX_ENV="prod" \
            --strategy bluegreen \
            --wait-timeout 300
        working-directory: ./ws
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
