name: WebSocket CI/CD

on:
  push:
    branches: [master, staging]
    paths:
      - 'ws/**'
      - '.github/workflows/ws.yml'
  pull_request:
    branches: [master, staging, dev]
    paths:
      - 'ws/**'
      - '.github/workflows/ws.yml'

jobs:
  test:
    name: Test WebSocket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'

      - name: Install Dependencies
        working-directory: ./ws
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run Tests
        working-directory: ./ws
        run: mix test

  deploy:
    name: Deploy WebSocket
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging')
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
    concurrency: ${{ github.ref == 'refs/heads/master' && 'production_ws' || 'staging_ws' }}

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          APP_NAME=${{ github.ref == 'refs/heads/master' && 'concord-ws' || 'concord-ws-staging' }}
          URL=${{ github.ref == 'refs/heads/master' && 'wss://concord-ws.fly.dev' || 'wss://staging.ws.concord.fly.dev' }}
          WEB_URL=${{ github.ref == 'refs/heads/master' && 'https://concord-web.fly.dev' || 'https://staging.concord.fly.dev' }}

          flyctl deploy --remote-only --app $APP_NAME \
            --dockerfile Dockerfile \
            --config fly.toml \
            --env URL="$URL" \
            --env CORS_ORIGIN="$WEB_URL" \
            --env MIX_ENV="prod" \
            --strategy bluegreen \
            --wait-timeout 300
        working-directory: ./ws
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
