app = "concord-web"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  HOSTNAME = "0.0.0.0"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  soft_stop = true
  routers = 2

  [[http_service.checks]]
    grace_period = "180s"
    interval = "30s"
    method = "GET"
    timeout = "30s"
    path = "/api/health"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "bluegreen"
  wait_timeout = "360s"
